export { tr }

const trDictionary = {
    'CreateInstantInvite': 'Создание приглашения',
    'KickMembers': 'Выгонять участников',
    'BanMembers': 'Банить участников',
    'Administrator': 'Администратор',
    'ManageChannels': 'Управлять каналами',
    'ManageGuild': 'Управлять сервером',
    'AddReactions': 'Добавлять реакции',
    'ViewAuditLog': 'Просматривать журнал аудита',
    'PrioritySpeaker': 'Приоритетный режим',
    'Stream': 'Видео',
    'ViewChannel': 'Читать текстовые каналы и видеть голосовые каналы',
    'SendMessages': 'Отправлять сообщения',
    'SendTtsMessages': 'Отправлять TTS сообщения',
    'ManageMessages': 'Управлять сообщениями',
    'EmbedLinks': 'Встраивать ссылки',
    'AttachFiles': 'Прикреплять файлы',
    'ReadMessageHistory': 'Читать историю сообщений',
    'MentionEveryone': 'Упоминание @everyone, @here и всех ролей',
    'UseExternalEmojis': 'Использовать внешние эмодзи',
    'ViewGuildInsights': 'Просмотр аналитики сервера',
    'Connect': 'Подключаться',
    'Speak': 'Говорить',
    'MuteMembers': 'Отключать участникам микрофон',
    'DeafenMembers': 'Отключать участникам звук',
    'MoveMembers': 'Перемещать участников',
    'UseVad': 'Приоритетный режим',
    'ChangeNickname': 'Изменять никнейм',
    'ManageNicknames': 'Управлять никнеймами',
    'ManageRoles': 'Управлять ролями',
    'ManageWebhooks': 'Управлять вебхуками (webhooks)',
    'ManageEmojisAndStickers': 'Управлять эмодзи',
    'desktop': 'ПК',
    'web': 'браузер',
    'mobile': 'телефон',
    'Playing': 'Играет в',
    'Streaming': 'Стримит',
    'Listening': 'Слушает',
    'Watching': 'Смотрит',
    'ru_from': 'Русского',
    'en_from': 'Английского',
    'de_from': 'Немецкого',
    'es_from': 'Испанского',
    'fr_from': 'Французского',
    'he_from': 'Иврита',
    'it_from': 'Итальянского',
    'pl_from': 'Польского',
    'ar_from': 'Арабского',
    'nl_from': 'Нидерландского',
    'zh_from': 'Китайского',
    'pt_from': 'Португальского',
    'rm_from': 'Романского',
    'tr_from': 'Турского',
    'ja_from': 'Японского',
    'ru_to': 'Русский',
    'en_to': 'Английский',
    'de_to': 'Немецкий',
    'es_to': 'Испанский',
    'fr_to': 'Французский',
    'he_to': 'Иврит',
    'it_to': 'Итальянский',
    'pl_to': 'Польский',
    'ar_to': 'Арабский',
    'nl_to': 'Нидерландский',
    'zh_to': 'Китайский',
    'pt_to': 'Португальский',
    'rm_to': 'Романский',
    'tr_to': 'Турский',
    'ja_to': 'Японский'
}

function tr(key: string): string {
    if (trDictionary.hasOwnProperty(key)) return trDictionary[key]
    return key
}