export { tr }

const trDictionary = {
    'CREATE_INSTANT_INVITE': 'Создание приглашения',
    'KICK_MEMBERS': 'Выгонять участников',
    'BAN_MEMBERS': 'Банить участников',
    'ADMINISTRATOR': 'Администратор',
    'MANAGE_CHANNELS': 'Управлять каналами',
    'MANAGE_GUILD': 'Управлять сервером',
    'ADD_REACTIONS': 'Добавлять реакции',
    'VIEW_AUDIT_LOG': 'Просматривать журнал аудита',
    'PRIORITY_SPEAKER': 'Приоритетный режим',
    'STREAM': 'Видео',
    'VIEW_CHANNEL': 'Читать текстовые каналы и видеть голосовые каналы',
    'SEND_MESSAGES': 'Отправлять сообщения',
    'SEND_TTS_MESSAGES': 'Отправлять TTS сообщения',
    'MANAGE_MESSAGES': 'Управлять сообщениями',
    'EMBED_LINKS': 'Встраивать ссылки',
    'ATTACH_FILES': 'Прикреплять файлы',
    'READ_MESSAGE_HISTORY': 'Читать историю сообщений',
    'MENTION_EVERYONE': 'Упоминание @everyone, @here и всех ролей',
    'USE_EXTERNAL_EMOJIS': 'Использовать внешние эмодзи',
    'VIEW_GUILD_INSIGHTS': 'Просмотр аналитики сервера',
    'CONNECT': 'Подключаться',
    'SPEAK': 'Говорить',
    'MUTE_MEMBERS': 'Отключать участникам микрофон',
    'DEAFEN_MEMBERS': 'Отключать участникам звук',
    'MOVE_MEMBERS': 'Перемещать участников',
    'USE_VAD': 'Приоритетный режим',
    'CHANGE_NICKNAME': 'Изменять никнейм',
    'MANAGE_NICKNAMES': 'Управлять никнеймами',
    'MANAGE_ROLES': 'Управлять ролями',
    'MANAGE_WEBHOOKS': 'Управлять вебхуками (webhooks)',
    'MANAGE_EMOJIS': 'Управлять эмодзи',
    'desktop': 'ПК',
    'web': 'браузер',
    'mobile': 'телефон',
    'PLAYING': 'Играет в',
    'STREAMING': 'Стримит',
    'LISTENING': 'Слушает',
    'WATCHING': 'Смотрит',
    'ru_from': 'Русского',
    'en_from': 'Английского',
    'de_from': 'Немецкого',
    'es_from': 'Испанского',
    'fr_from': 'Французского',
    'he_from': 'Иврита',
    'it_from': 'Итальянского',
    'pl_from': 'Польского',
    'ar_from': 'Арабского',
    'nl_from': 'Нидерландского',
    'zh_from': 'Китайского',
    'pt_from': 'Португальского',
    'rm_from': 'Романского',
    'tr_from': 'Турского',
    'ja_from': 'Японского',
    'ru_to': 'Русский',
    'en_to': 'Английский',
    'de_to': 'Немецкий',
    'es_to': 'Испанский',
    'fr_to': 'Французский',
    'he_to': 'Иврит',
    'it_to': 'Итальянский',
    'pl_to': 'Польский',
    'ar_to': 'Арабский',
    'nl_to': 'Нидерландский',
    'zh_to': 'Китайский',
    'pt_to': 'Португальский',
    'rm_to': 'Романский',
    'tr_to': 'Турский',
    'ja_to': 'Японский'
}

function tr(key: string): string {
    if (trDictionary.hasOwnProperty(key)) return trDictionary[key]
    return key
}